### ISSUE TITLE
Ajouter des exemples pour certains verbes

### ISSUE THREAD

**Issue by Olon11** [profcfuhrmanets/exemples-ts#1]
- [x] GET
- [x] POST
- [x] PATCH
- [x] PUT
- [x] DELETE

**Comment by Olon11** [comment]
@fuhrmanator J'ai ajouté un exemple pour tous les verbes avec une explication. Par contre, je n'ai pas fait de gestion d'erreurs pour simplifier. Si tu le souhaites, je peux le faire. Sinon, je vais seulement ajouter un avertissement.

Une fois approuvé, je vais modifier le README pour montrer comment utiliser l'exemple.

**Comment by fuhrmanator** [comment]
Un but du squelette est de simplifier. Il n'est pas nécessaire de faire la
solution avec plus que GET. Mais pour ceux qui veulent aller plus loin, des
exemples bien faits seraient utiles. Si le squelette peut présenter une
alternative ainsi qu'une référence pour d'autres verbes et le contrôle
d'erreurs, ça sera suffisant.

**Comment by Olon11** [comment]
Ce n'est pas le repo du squelette 😉. Je vais ajouter un avertissement pour la gestion des erreurs dans ce cas
